chore!: test suite updated
mineiros-io/terraform-google-bigquery-dataset pull request #15
Opened 2022-09-12 15:39 UTC by waxb

- chore: changelog updated
- chore: test suite updated

2022-09-12 20:11 UTC, soerenmartius requested changes

2022-09-12 20:11 UTC, soerenmartius commented on CONTRIBUTING.md
> +
this isn't the latest version of `CONTRIBUTING.md`, please see https://github.com/mineiros-io/terraform-module-template/pull/164 for details

2022-09-12 20:11 UTC, soerenmartius commented on CHANGELOG.md
> +- Test suite updated
```suggestion

### Added

- Add unit tests
```

2022-09-13 09:58 UTC, mariux requested changes

2022-09-13 09:58 UTC, mariux commented on README.tfdoc.hcl
> +          type        = any
```suggestion
          type        = list(access)
```

2022-09-13 09:58 UTC, mariux commented on README.tfdoc.hcl
> +          type        = any
```suggestion
          type        = list(iam)
```

2022-09-13 10:49 UTC, mariux commented on CHANGELOG.md
> +- Test suite updated
not resolved yet.

2022-09-14 17:42 UTC, mariux requested changes

2022-09-14 17:42 UTC, mariux commented on CHANGELOG.md
> +
```suggestion
### Added

- Add unit tests

```

2022-09-19 20:21 UTC, mariux requested changes
- tests are failing -> not ready for review
- please mark the breaking commit not only the PR.

2022-09-19 20:22 UTC, mariux reviewed
There are still unresolved change requests ;)

2022-09-19 20:22 UTC, mariux commented on CHANGELOG.md
> +
not resolved yet.

2022-09-19 20:22 UTC, mariux commented on CHANGELOG.md
> +- BREAKING: Support for provider 3.x
```suggestion
- BREAKING: Support for provider 3.x removed
```

2022-09-20 10:55 UTC, mariux requested changes

2022-09-20 10:55 UTC, mariux commented on CHANGELOG.md
> +- BREAKING: Support for provider 3.x
```suggestion
- BREAKING: Remove support for Terraform versions before v1.0
- BREAKING: Remove support for Terraform Google Provider versions before v4.0
```

2022-09-20 10:56 UTC, mariux approved these changes
lgtm thanks ;)

2022-09-20 11:52 UTC, soerenmartius approved these changes
lgtm

2022-09-20 11:55 UTC, merged