Add terradoc
mineiros-io/terraform-google-bigquery-dataset pull request #8
Opened 2021-12-09 02:25 UTC by kassianh

Recreated README with terradoc, checked documentation for errors or inconsistencies.

2021-12-13 18:46 UTC, mariux requested changes

2021-12-13 18:46 UTC, mariux commented on Makefile
> +rm-command    = $(call quiet-command,rm -rf ${1},"${YELLOW}[CLEAN] ${GREEN}${1}${RESET}")
please fix EOL at EOF in all PRs and maybe fix you editor settings ;)

2021-12-13 18:53 UTC, mariux requested changes
please fix those issues in all open pRs and future ones..

2021-12-13 18:53 UTC, mariux commented on README.tfdoc.hcl
> +          type           = list(any)
```suggestion
          type           = any
```

2021-12-13 18:53 UTC, mariux commented on README.tfdoc.hcl
> +          END
complex types are just `list(type)`  we do not expand objects as we explain eahc attribute anyway.

is role a list of roles? looks like the naming is bad but can be fixed at another time..



```suggestion
          readme_type = <<-END
            list(object({
            role           = string
            special_group  = string
            group_by_email = string
            user_by_email  = string
          }))
          END
```

2021-12-13 18:53 UTC, mariux commented on README.tfdoc.hcl
> +            (Optional) google bigquery dataset iam choice whether 'authoritative == true' use google_bigquery_iam_binding, 'authoritative == false' use google_bigquery_iam_member
this text is outdated... please replace whenever you see this.

```suggestion
            Whether to exclusively set (authoritative mode) or add (non-authoritative/additive mode) members to the role.
```

2021-12-13 18:53 UTC, mariux commented on README.tfdoc.hcl
> +          END
wrong indent..

```suggestion
            description = <<-END
              The role that should be applied. Note that custom roles must be of the format [projects|organizations]/{parent-name}/roles/{role-name}.
            END
```

2021-12-14 00:28 UTC, soerenmartius submitted a review, later dismissed

2021-12-14 00:28 UTC, soerenmartius commented on README.tfdoc.hcl
> +              The ID of the dataset containing this table.
this seems to be mixed up with the variable below? this is the table_id and not the dataset id?

2021-12-14 00:28 UTC, soerenmartius commented on README.tfdoc.hcl
> +              The ID of the table.
I guess here we need to use the description of the variable above?

2021-12-15 21:16 UTC, mariux submitted a review, later dismissed

2021-12-15 21:16 UTC, mariux commented on README.tfdoc.hcl
> +      title   = "Google Documentation:"
```suggestion
      title   = "Google Documentation"
```

2021-12-15 21:16 UTC, mariux commented on README.tfdoc.hcl
> +      title   = "Terraform Google Provider Documentation:"
```suggestion
      title   = "Terraform Google Provider Documentation"
```

2021-12-16 15:51 UTC, i4ki approved these changes
lgtm

2021-12-16 22:14 UTC, merged